= 妈妈不用担心我的英语
pxzxj; pudge.zxj@gmail.com; 2025/05/07

== 外刊精读138 / 无需将人类大脑与人工智能做对比

bilibili::BV1KLjPz2EHB[]

[red]#biased adj. 有偏见的 (bias n. 偏见 unbiased adj. 公正的)#

malleable / ˈmæliəb(ə)l / adj. 容易改变的，易受影响的(easily influenced, trained, or controlled)

(Mother wanted me to be a malleable girl who would take her advice.)

1.

[red]#generate v. 造成，产生(to cause sth to exist)#

这个社会问题引起了广泛的关注。

'''

[red]#at the threshold of 面对，即将#

因为科技的快速发展，很多行业都面临着重大的变革。

'''

throw somebody under the bus 为了个人利益出卖/牺牲某人

2.

[red]#capability n. 能力 (the ability to do sth)#

很多汽车生产商都在研发拥有自动驾驶能力的汽车。

'''

[red]#sceptical adj. 怀疑的#

很多人怀疑自动驾驶汽车的安全性。

'''

[red]#foreseeable adj. 可预见的 (in the foreseeable future)#

在可预见的未来，探索太空的努力会给我们带来巨大的回报。

'''

3.

incrementally / ˌɪŋkrəˈmentəli / adv. 循序渐进地

plough through 费力地做某事

take down 击败

grid n. 高压输电网

incandescent adj. 白炽的

pixel / ˈpɪksl / n. 像素

[red]#glance n. 一瞥#

4.

brittle adj. 脆弱的

deviate from 偏离，违背

[red]#result in 导致#

法律的缺失导致这样的问题越来越多。

'''

[red]#release v. 放开，释放#

[red]#(to give freedom or free movement to sb or sth)#

[red]#(release control/constraint)#

5.

semantic / sɪˈmæntɪk / adj. 语义的

[red]#accumulate v. 积累#

[red]#(to collect a large number of things over a long period of time)#

[red]#(Customers can accumulate points through consumption.)#

对于大学生来说，暑假兼职工作可以帮助他们积累更多的社会经验。

'''

episodic / ˌepɪˈsɑːdɪk / adj. 偶然发生的

beak n. 喙

6.

emulate v. 效仿

(They hope to emulate the success of other companies.)

startlingly adv. 令人惊讶地

fragmented adj. 分裂的，破碎的

(consisting of several separate parts)

malleable adj. 易受外界影响的

[red]#navigate v. 处理，应对#

[red]#(For very young children, navigating a multilingual environment imparts advantages that transfer far beyond language.)#

[red]#comprehensive adj. 全面的，综合的#

这本书全面地记录了那个时期的历史。

'''

[red]#body n. 大量的 (a large amount of sth)#

[red]#(There is a growing body of evidence to support their claim.)#

[red]#(a huge/substantial body of knowledge/experience)#

7.

[red]#constraint n. 限制，束缚#

每个人的行为都应受到法律的限制。

'''

[red]#physical adj. 物质的，有形的(relating to things you can see or touch#)

[red]#(All physical objects occupy space.)#

[red]#squeeze v. 挤压，捏 (squeeze as much profit as possible)#

a needle in a haystack 大海捞针

overwhelm v. 击败

frugal adj. 节俭的，朴素的

8.

[red]#rather than 而不是#

我们应该想方设法地解决问题，而不是否认或视而不见。

'''

[red]#surpass v. 超过，优于(to do or be better than) (exceed/outperform)#

这款产品的销量已经超过了之前最大胆的估计。

'''

complement v.&n. 补充

idiosyncrasy / ˌɪdiəˈsɪŋkrəsi / n. 怪癖

progeny / ˈprɑːdʒəni / n. 后代

1. 这个社会问题引起了广泛的关注
+

'''

2. 因为科技的快速发展，很多行业都面临着重大的变革
+

'''

3. 很多汽车生产商都在研发拥有自动驾驶能力的汽车
+

'''

4. 很多人怀疑自动驾驶汽车的安全性
+

'''

5. 在可预见的未来，探索太空的努力会给我们带来巨大的回报
+

'''

6. 法律的缺失导致这样的问题越来越多
+

'''

7. 对于大学生来说，暑假兼职工作可以帮助他们积累更多的社会经验
+

'''

8. 这本书全面地记录了那个时期的历史
+

'''

9. 每个人的行为都应受到法律的限制
+

'''

10. 我们应该想方设法地解决问题，而不是否认或视而不见
+

'''

11. 这款产品的销量已经超过了之前最大胆的估计
+

'''


=== 137期文章造句练习参考

曾经很多人都认为对于年轻人来说考上好大学是唯一通向成功的道路

There was a widespread/prevailing notion that being admitted to a good
university is the only path to success.

2024年，日本的婴儿出生率高于韩国的婴儿出生率

In 2024, Japan’s birth rate was higher than Korean’s counterpart.

支持立法惩罚未成年犯罪者的人认为这是减少未成年犯罪率的必要措施

The proponents of legislating penalties for juvenile offenders reckon
that it is an essential measure to reduce underage crime rates.

很多人认为这个问题已经到了不容忽视的地步了

Many people reckon that this issue has reached a point where it cannot
be ignored any more.

放开对生育的限制是利大于弊的

The benefits of lifting birth constraint outweigh the disadvantages.

[big]*#以下是错例：#*

infant birth rate

proponents who advocate/support…..

proponents of legislation of penalty to juvenile delinquency reckon that
setting a law is an essential measure to reduce its counterpart.

Lifting the limit on giving birth is the good outweigh the bad
