:toc:
= 妈妈不用担心我的英语
pxzxj; pudge.zxj@gmail.com; 2025/05/07

== 外刊精读138 / 无需将人类大脑与人工智能做对比

bilibili::BV1KLjPz2EHB[]

[red]#biased adj. 有偏见的 (bias n. 偏见 unbiased adj. 公正的)#

malleable / ˈmæliəb(ə)l / adj. 容易改变的，易受影响的(easily influenced, trained, or controlled)

(Mother wanted me to be a malleable girl who would take her advice.)

1.

[red]#generate v. 造成，产生(to cause sth to exist)#

这个社会问题引起了广泛的关注。

'''

[red]#at the threshold of 面对，即将#

因为科技的快速发展，很多行业都面临着重大的变革。

'''

throw somebody under the bus 为了个人利益出卖/牺牲某人

2.

[red]#capability n. 能力 (the ability to do sth)#

很多汽车生产商都在研发拥有自动驾驶能力的汽车。

'''

[red]#sceptical adj. 怀疑的#

很多人怀疑自动驾驶汽车的安全性。

'''

[red]#foreseeable adj. 可预见的 (in the foreseeable future)#

在可预见的未来，探索太空的努力会给我们带来巨大的回报。

'''

3.

incrementally / ˌɪŋkrəˈmentəli / adv. 循序渐进地

plough through 费力地做某事

take down 击败

grid n. 高压输电网

incandescent adj. 白炽的

pixel / ˈpɪksl / n. 像素

[red]#glance n. 一瞥#

4.

brittle adj. 脆弱的

deviate from 偏离，违背

[red]#result in 导致#

法律的缺失导致这样的问题越来越多。

'''

[red]#release v. 放开，释放#

[red]#(to give freedom or free movement to sb or sth)#

[red]#(release control/constraint)#

5.

semantic / sɪˈmæntɪk / adj. 语义的

[red]#accumulate v. 积累#

[red]#(to collect a large number of things over a long period of time)#

[red]#(Customers can accumulate points through consumption.)#

对于大学生来说，暑假兼职工作可以帮助他们积累更多的社会经验。

'''

episodic / ˌepɪˈsɑːdɪk / adj. 偶然发生的

beak n. 喙

6.

emulate v. 效仿

(They hope to emulate the success of other companies.)

startlingly adv. 令人惊讶地

fragmented adj. 分裂的，破碎的

(consisting of several separate parts)

malleable adj. 易受外界影响的

[red]#navigate v. 处理，应对#

[red]#(For very young children, navigating a multilingual environment imparts advantages that transfer far beyond language.)#

[red]#comprehensive adj. 全面的，综合的#

这本书全面地记录了那个时期的历史。

'''

[red]#body n. 大量的 (a large amount of sth)#

[red]#(There is a growing body of evidence to support their claim.)#

[red]#(a huge/substantial body of knowledge/experience)#

7.

[red]#constraint n. 限制，束缚#

每个人的行为都应受到法律的限制。

'''

[red]#physical adj. 物质的，有形的(relating to things you can see or touch#)

[red]#(All physical objects occupy space.)#

[red]#squeeze v. 挤压，捏 (squeeze as much profit as possible)#

a needle in a haystack 大海捞针

overwhelm v. 击败

frugal adj. 节俭的，朴素的

8.

[red]#rather than 而不是#

我们应该想方设法地解决问题，而不是否认或视而不见。

'''

[red]#surpass v. 超过，优于(to do or be better than) (exceed/outperform)#

这款产品的销量已经超过了之前最大胆的估计。

'''

complement v.&n. 补充

idiosyncrasy / ˌɪdiəˈsɪŋkrəsi / n. 怪癖

progeny / ˈprɑːdʒəni / n. 后代

1. 这个社会问题引起了广泛的关注
+

'''

2. 因为科技的快速发展，很多行业都面临着重大的变革
+

'''

3. 很多汽车生产商都在研发拥有自动驾驶能力的汽车
+

'''

4. 很多人怀疑自动驾驶汽车的安全性
+

'''

5. 在可预见的未来，探索太空的努力会给我们带来巨大的回报
+

'''

6. 法律的缺失导致这样的问题越来越多
+

'''

7. 对于大学生来说，暑假兼职工作可以帮助他们积累更多的社会经验
+

'''

8. 这本书全面地记录了那个时期的历史
+

'''

9. 每个人的行为都应受到法律的限制
+

'''

10. 我们应该想方设法地解决问题，而不是否认或视而不见
+

'''

11. 这款产品的销量已经超过了之前最大胆的估计
+

'''


=== 137期文章造句练习参考

曾经很多人都认为对于年轻人来说考上好大学是唯一通向成功的道路

There was a widespread/prevailing notion that being admitted to a good
university is the only path to success.

2024年，日本的婴儿出生率高于韩国的婴儿出生率

In 2024, Japan’s birth rate was higher than Korean’s counterpart.

支持立法惩罚未成年犯罪者的人认为这是减少未成年犯罪率的必要措施

The proponents of legislating penalties for juvenile offenders reckon
that it is an essential measure to reduce underage crime rates.

很多人认为这个问题已经到了不容忽视的地步了

Many people reckon that this issue has reached a point where it cannot
be ignored any more.

放开对生育的限制是利大于弊的

The benefits of lifting birth constraint outweigh the disadvantages.

[big]*#以下是错例：#*

infant birth rate

proponents who advocate/support…..

proponents of legislation of penalty to juvenile delinquency reckon that
setting a law is an essential measure to reduce its counterpart.

Lifting the limit on giving birth is the good outweigh the bad

== 外刊精读139 /Washington Post / 美国学生贷款新规

bilibili::BV1Pij2zAET9[]

House Republicans 众议院共和党议员

Pell Grant 佩尔助学金 （美国联邦政府为低收入家庭学生提供的助学金，与贷款不同，无需还款）

1.

[red]#embark on/upon 开始 (to start sth new or important)#

[red]#(We’re embarking on a new project later this year.)#

[red]#wholesale adj. 全面的，大规模的 (wholesale changes/destruction)#

[red]#shake up 对…做出重大调整#

[red]#(Technological changes have shaken up many industries.)#

[red]#advance v. 使发展，推进#

他的研究工作极大地促进了这个研究领域的发展。

'''

[red]#conservative adj. 保守的(not usually liking or trusting change)#

老年人往往很保守，对任何新的事物都有些怀疑。

'''
[red]#agenda n. 议事日程#

curtail v. 限制，缩减 (curtail spending/budget)

2.

[red]#legislation n. 法律；立法#

[red]#(The effects of this legislation will extend further than the government intends.)#

政府应该通过立法来限制汽车尾气排放。

'''

[red]#access to 使用；得到#

[red]#(The system has been designed to give the user quick and easy access to
the required information.)#

网络的普及能够让更多人得到学习的机会。

'''

3.

chambers of Congress 国会议院(众议院&参议院)

(Senators 参议员 Representatives 众议员)

[red]#slim adj. 苗条的；非常小的 (slim majority/margin/chance/hope)#

[red]#(They only have a slim chance of winning.)#

[red]#margin n. 差额(the amount by which one thing is different from
another)#

[red]#(She won the presidency by a wide/slim/thin/narrow margin.)#

flesh out 以细节充实(to add more details or information to sth)

[red]#implement v. 实施，贯彻 (to start using a plan or system)#

[red]#(The changes to the national health system will be implemented next
year.)#

reconciliation / ˌrekənsɪliˈeɪʃ(ə)n / n. 和谐一致；对账

[red]#craft v. 制作； n. 工艺，手工艺#

4.

unveil v. 展示，介绍 (veil n. 面纱)

[red]#package n. 一整套；套餐#

[red]#(The hotel and airfare are all part of our vacation package.)#

5.

deliver on 实现

streamline v. 简化

[red]#lending n. 贷款#

[red]#mirror v. 反映#

移动支付的普及反映了人们消费习惯的变化。

'''

[red]#curb v.&n. 控制，限制，约束 (constrain/limit/restrict)#

[red]#(The legislation is intended to curb price increases.)#

支持控枪的人认为这是保护公民安全的必要措施。

'''

6.

sweeping adj. 影响广泛的，大的

(sweeping changes 大刀阔斧的改革 sweeping cuts大幅削减

sweeping statement 泛泛之谈 sweeping victory 大获全胜)

reauthorization 重新批准，再次授权

7.

termination n. 终止

[red]#get rid of 清除，丢弃，摆脱#

[red]#mitigate v. 缓和，减轻#

科学家们试图通过一些合理的办法来缓解气候变化会人类的影响。

'''

[red]#enroll v. 录取，录取#

8.

aggregate n. 总数

cap n. 限额，限制

11.

[red]#impose v. 推行，强制实行(to officially force a rule, tax, punishment, etc. to be obeyed or received)#

酒驾应该处以重罚。( … be imposed on… )

'''

attendance n. 出席，参加

15.

whittle sth down 缩减

16.

[red]#tie up 捆绑，缠住#

[red]#offset v. 弥补，抵消#

[red]#(Apple may be able to offset a dip in China with growth in India.)#

stall v. 搁置

get one’s way 如愿以偿

17.

tier n. 一层； v. 分层，分级 (3-tier city)

principal n. 本金 outstanding principal 未偿本金

19.

enrollee / ɪnˌroʊˈliː / n. 被录取的人，入学者

waive v. 放弃 (to not demand sth you have a right to)

amortization n. 摊销(the process of reducing a cost or total in regular small amounts)

20.

balance n. 结余

21.

loan forgiveness 贷款豁免

[red]#out of reach 得不到， 没有 (within/in reach)#

[red]#(Safe drinking water is out of reach for around one billion people in
the world.)#

对于一些低收入的美国家庭来说，他们无法享受优质的医疗服务。

'''

[red]#postpone v. 推迟，延缓#

[red]#(They decided to postpone their holiday until next year.)#

deferment / dɪˈfɜːrmənt / n. 延期

22.

[red]#across the board 全面的， 影响到各个领域的#

[red]#(The improvement has been across the board, with all divisions either increasing profits or reducing losses.)#

[red]#(The plan has across-the-board support.)#

23.

eligibility n. 有资格，符合条件

[red]#credit n. 学分#

[red]#credit hour 学分小时 (获得一个学分所需要的学习时间)#

24.

[red]#register v. 注册，登记#

[red]#recipient n. 接受者#

25.

[red]#attain v. 获得#

我们需要制定一个达到目标的最佳方案。

'''

[red]#jeopardize / ˈdʒepərdaɪz / v. 危及，损害#

这样的生活习惯可能会损害健康。

'''

unmet adj. 未实现的，不满意的

26.

[red]#asset n. 资产，财产 (liquid asset fixed asset)#

27.

as it stands 按照现在的情况

[red]#qualify v. 有资格，有权#

18岁以上的人才有资格参加比赛。

'''

28.

[red]#duration n. 持续时间#

bipartisan adj. 包括两个党派的，为两党所支持的

[red]#draw v. 吸引，引起#

这款产品吸引了超过一百万消费者。

'''

unscrupulous / ʌnˈskruːpjələs / adj. 肆无忌惮的，没有道德底线的

29.

stave off 挡住，避开

looming adj. 逼近的，迫在眉睫的

shortfall n. 缺口，差额

30.

skin in the game 切身利益

(Being a co-founder, I certainly have skin in the game and want to see our startup thrive.)

delinquent adj. 不良的，违法的 (illegal or not acceptable, or behaving in a way that is illegal or not acceptable)

31.

gravy train 发横材

accountability n. 问责，负责

35.

unintended adj. 无意的，无心的，意想不到的

[red]#preserve v. 保留，保护#

[red]#incentive n. 激励#

37.

[red]#vocational adj. 职业的 (They regard vocational training as a part of a young person’s education.)#

[red]#bar v. 禁止，阻止 (bar someone from something)#

[red]#for-profit adj. 营利性的 (non-profit / not-for-profit)#

38.

[red]#exploit v. 利用(to use sth in a way that helps you); 剥削#

1. 他的研究工作极大地促进了这个研究领域的发展。
+

'''

2. 老年人往往很保守，对任何新的事物都有些怀疑。
+

'''

3. 政府应该通过立法来限制汽车尾气排放。
+

'''

4. 网络的普及能够让更多人得到学习的机会。
+

'''

5. 移动支付的普及反映了人们消费习惯的变化。
+

'''

6. 支持控枪的人认为这是保护公民安全的必要措施。
+

7. 科学家们试图通过一些合理的办法来缓解气候变化会人类的影响。
+

'''

8. 酒驾应该处以重罚。( … be imposed on… )
+

'''

9. 对于一些低收入的美国家庭来说，他们无法享受优质的医疗服务。
+

'''

10. 我们需要制定一个达到目标的最佳方案。
+

'''

11. 这样的生活习惯可能会损害健康。
+

'''

12. 18岁以上的人才有资格参加比赛。
+

'''

13. 这款产品吸引了超过一百万消费者。
+

'''

=== 138期句子翻译练习参考

1. 这个社会问题引起了广泛的关注。
+
This societal issue has generated widespread concern.

2. 因为科技的快速发展，很多行业都面临着重大的变革。
+
With the rapid development of technology, many industries are at the threshold of groundbreaking revolution.

3. 很多汽车生产商都在研发拥有自动驾驶能力的汽车。
+
Many car manufacturers are developing vehicles with self-driving capability.

4. 很多人怀疑自动驾驶汽车的安全性。
+
Many people are sceptical about the safety of self-driving automobiles.

5. 在可预见的未来，探索太空的努力会给我们带来巨大的回报。
+
In the foreseeable future, the efforts of space exploration will bring us huge rewards.

6. 法律的缺失导致这样的问题越来越多。
+
The absence of legislation results in an increasing number of such problems.

7. 对于大学生来说，暑假兼职工作可以帮助他们积累更多的社会经验。
+
For college students, part-time jobs in summer vacation can help them accumulate more social experience.

8. 这本书全面地记录了那个时期的历史。
+
There is a comprehensive recording of that period of history in the book.

9. 每个人的行为都应受到法律的限制。
+
Every individual’s behavior should be under the constraint of laws.

10. 我们应该想方设法地解决问题，而不是否认或视而不见。
+
We should make every effort to solve problems, rather than deny or turn
a blind eye to them.

11. 这款产品的销量已经超过了之前最大胆的估计。
+
The sales of this product have surpassed the wildest estimates before.

== 外刊精读140 / Science / 美国数据统计系统

bilibili::BV1dLKtzqEEh[]

1.

[red]#critical adj. 至关重要的 (of the greatest importance)#

各方的配合是这个方案成功的关键因素。

'''

[red]#flourish vi. 繁荣， 蓬勃发展(to grow or develop successfully)#

稳定的国家政策能够在很大程度上促进各行各业的繁荣发展。

'''

[red]#manner n. 种类，类型 (all manner of sth 各种各样的)#

[red]#informed adj. 了解情况的 (well-informed adj. 见多识广的)#

广告宣传能够让消费者在够买商品的时候做出有根据的选择。

'''

[red]#context n. 环境，背景#

[red]#notably adv. 特别地；明显地#

上个季度的销量下降尤为明显。

'''

[red]#amid  /əˈmɪd/ prep. 在…当中#

upheaval n. 动荡，剧变

harness v. 掌控，利用(to control sth, usually in order to use its power)

Reliable, relevant, statistical information helps +
#businesses to invest and flourish; +
governments at the local, state and national levels to make +
critical decisions on policy and public services;# +
#and individuals and families to invest in their future.#

2.

premier  /prɪˈmɪr/ adj. 首位的， 首要的

aggregate  /ˈæɡrəɡeɪt/ v. 聚集

subscription n. 订阅

underpinning n. 基础，根基 (support, strength, or the basic structure of sth)

3.

hamper v. 妨碍，阻碍

[red]#bold adj. 勇敢的#

counter v. 反抗，对抗

burgeoning / ˈbɜːrdʒənɪŋ / adj. 迅速发展的

predate / ˌpriːˈdeɪt / vt. 早于….(to have existed or happened before another thing)

[red]#imperative / ɪmˈperətɪv / adj. &n. 极重要的 (extremely important or urgent)#

4.

[red]#blend v. & n. 融合，混合#

[red]#(Their music is a blend of jazz and hip-hop.)#

5.

[red]#prior to 在…之前 (before)#

[red]#squeeze v. 挤压#

incremental / ɪnkrəˈməntl / adj. 递增的，渐进的

optimally / ˈɑːptɪməli / adv. 最佳地

[red]#stretch v. 到…的限度，竭尽 (Many families’ budgets are already stretched to breaking point.)#

inhibit v. 抑制，约束

prioritization / praɪˌɔːrətəˈzeɪʃn / n. 优先次序

6.

consolidated adj. 加强的，巩固的

[red]#stand out 显眼，突出，出众 (to be noticeable)#

她在众多申请这个职位的人当中脱颖而出。

'''

avail  /əˈveɪl/ n. 效用，帮助

territoriality / ˌterəˌtɔːriˈæləti / n. 领土权

7.

agility n. 敏捷，灵活

statutory / ˈstætʃətɔːri / adj. 法定的(decided or controlled by law)

confidentiality / ˌkɑːnfɪˌdenʃiˈæləti / n. 秘密，机密

[red]#execute v. 实施，执行 (to execute a deal/plan)#

[red]#policy-driven adj. 政策驱动的#

[red]#(money-driven person， tourism-driven city， market-driven economy)#

工作与娱乐的区别在于，前者是目的导向的，后者是过程导向的。

'''

[red]#objectivity n. 客观(objective 客观的)#

[red]#irreplaceable adj. 不可替代的，独一无二的#

We urge the administration to +
#reorganize the statistical system, +
with particular care to improve agility by reducing barriers to sharing data and coordination while maintaining strong statutory privacy and confidentiality protections for statistical data;#

#achieve economies of scale and scope across statistical agencies +
by sharing expertise, information technology, training, software, sample frames, and data standards;#

and #increase public trust +
by ensuring that the consolidated system can design and execute statistical methods outside of policy and political influence while remaining responsive to policy-driven needs.#

8.

dwindle v. 减少

[red]#civil adj. 平民的(not military or religious, or relating to the ordinary people of a country)#

[red]#(civil service 公务员 civil law 民法 civil use 民用 civilian 平民)#

vigorous adj. 充满活力的，强有力的

oversight n. 监管，监督

[red]#in accordance with 依照#

fragmented adj. 支离破碎的

[red]#community n. 社区，群体，团体，界(the people living in one particular area or people who are considered as a unit because of their common interests, social group, or nationality)#

[red]#(There is a large black/Chinese community living in this area.)#

他的研究引起了科学界的激烈争论。

'''

overdue adj. 过期的，延误的

[red]#deteriorate v. 恶化#

[red]#(The political situation in the region has deteriorated rapidly.)#

我们不能等到情况恶化以后才开始采取行动。

'''

1. 各方的配合是这个方案成功的关键因素。
+

'''

2. 稳定的国家政策能够在很大程度上促进各行各业的繁荣发展。
+

'''

3. 广告宣传能够让消费者在够买商品的时候做出有根据的选择。
+

'''

4. 上个季度的销量下降尤为明显。
+

'''

5. 她在众多申请这个职位的人当中脱颖而出。
+

'''

6. 工作与娱乐的区别在于，前者是目的导向的，后者是过程导向的。
+

'''

7. 他的研究引起了科学界的激烈争论。
+

'''

8. 我们不能等到情况恶化以后才开始采取行动。

=== 139期翻译练习参考

1. 他的研究工作极大地促进了这个研究领域的发展。
+

His research has greatly advanced the development of this field.

2. 老年人往往很保守，对任何新的事物都有些怀疑。
+

The elderly are always conservative and a bit sceptical about any novel things.

3. 政府应该通过立法来限制汽车尾气排放。
+

The government should limit the vehicle emission through legislation.

4. 网络的普及能够让更多人得到学习的机会。
+

More people can have easy access to the opportunity of learning thanks to the popularization of the Internet.

5. 移动支付的普及反映了人们消费习惯的变化。
+

The popularity of mobile payment mirrors the shift in people’s consumption habits.

6. 支持控枪的人认为这是保护公民安全的必要措施。
+

The proponents of curbing gun violence believe it’s the necessary measure to protect civilians.

7. 科学家们试图通过一些合理的办法来缓解气候变化会人类的影响。
+

Scientists are exploring viable measures to mitigate the impacts of
climate changes on humans.

8. 酒驾应该处以重罚。( … be imposed on… )
+

Heavy punishment should be imposed on drunk driving.

9. 对于一些低收入的美国家庭来说，他们无法享受优质的医疗服务。
+

For some American low-income families, high-quality medical service is out of their reach.

10. 我们需要制定一个达到目标的最佳方案。
+

We should develop the optimum plan to attain the goal.

11. 这样的生活习惯可能会损害健康。
+

Such living habits could jeopardize health.

12. 18岁以上的人才有资格参加比赛。
+

Only People over 18 can qualify for the competition.

13. 这款产品吸引了超过一百万消费者。
+

This product has drawn more than 1 million consumers.


